server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: New Web's Technologies course with NestJS
  description: The Album API description
  version: 1.0
  tag: album
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/alb
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
